### MENDAPATKAN SEMUA DATA ADMIN
GET http://195.35.8.190:4000/api/admin



### REGISTER ATAU MEMBUAT ADMIN BARU
POST http://195.35.8.190:4000/api/admin
Content-Type: application/json 

{
    "username" : "admin1",
    "password" : "admin",
    "re_password" : "admin" 
}

### MENDAPATKAN DATA ADMIN BERDASARKAN ID
GET http://localhost:4000/api/admin/1


### MELAKUKAN UPDATE DATA ADMIN BERDASARKAN ID
PATCH http://localhost:4000/api/admin/1
Content-Type: application/json

{
    "username" : "admin",
    "password" : "kesehatan",
    "re_password" : "kesehatan"
}

### MELAKUKAN DELETE DATA ADMIN BERDASARKAN ID
DELETE http://localhost:4000/api/admin/2



### MELAKUKAN LOGIN ADMIN
POST http://localhost:4000/api/admin/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "kesehatan"
}


