### MEMBUAT COMMENT BARU DI FORUM
POST http://195.35.8.190:4000/api/forum/comments
Content-Type: application/json

{
    "userId" : 5,
    "forumDiskusiId" : 3,
    "comment" : "Tes memberikan komentar pada salah satu forum diskusi"
}

### MENDAPATKAN SEMUA KOMENTAR BERDASARKAN ID FORUM
GET http://195.35.8.190:4000/api/forum/comments/3


### HAPUS COMMENT BERDASARKAN ID
DELETE http://localhost:4000/api/forum/comments/1