### MEMBUAT COMMENT BARU DI FORUM
POST http://localhost:4000/api/forum/comments
Content-Type: application/json

{
    "userId" : 5,
    "forumDiskusiId" : 1,
    "comment" : "Komentar satu"
}

### MENDAPATKAN SEMUA KOMENTAR BERDASARKAN ID FORUM
GET http://localhost:4000/api/forum/comments/1


### HAPUS COMMENT BERDASARKAN ID
DELETE http://localhost:4000/api/forum/comments/1