### MENDAPATKAN SEMUA DATA FORUM
GET http://localhost:4000/api/forum


### MENDAPATKAN DATA FORUM BERDASARKAN ID
GET http://localhost:4000/api/forum/1


### MEMBUAT THREAD
POST http://localhost:4000/api/forum
Content-Type: application/json

{
    "userId" : 7,
    "title" : "Diskusi Terbuka 1",
    "text" : "Ini diskusi terbuka"
}

### MENGHAPUS TREED BERDASARKAN ID
DELETE http://localhost:4000/api/forum/2