### LOGIN SEBAGAI ADMIN
POST  http://localhost:4000/api/login/admin
Content-Type: application/json

{
    "email" : "admin1@gmail.com",
    "password" : "kesehatan"
}

### LOGIN SEBAGAI USER
POST  http://localhost:4000/api/login/user
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "user1@gmail.com"
}