### MENDAPATKAN SEMUA DATA MESSAGE
GET http://localhost:4000/api/messages


### MEMBUAT PESAN BARU
POST http://localhost:4000/api/messages
Content-Type: application/json

{    
    "userId"        : 6,
    "message"       : "pesan sudah terkirim satu"
}



### MENGHAPUS DATA PESAN
DELETE http://localhost:4000/api/messages/1