### MENDAPATKAN DATA MUSIC
GET http://localhost:4000/api/musics

### MENDAPATKAN DATA MUSIC BERDASARKAN ID
GET http://localhost:4000/api/musics/1

### MENAMBAH DATA MUSIC
POST http://localhost:4000/api/musics
Content-Type: application/json

{
    "title" : "musik1",
    "url" : "https://www.mfiles.co.uk/mp3-downloads/angels-we-have-heard-on-high.mp3"
}

### UPDATE DATA MUSIC BERDASARKAN ID
PATCH  http://localhost:4000/api/musics/1
Content-Type: application/json

{
    "title" : "musik1 updated",
    "url" : "https://www.mfiles.co.uk/mp3-downloads/angels-we-have-heard-on-high.mp3"
}

### DELETE DATA MUSIC BERDASARKAN ID
DELETE http://localhost:4000/api/musics/1