### MENDAPATKAN SEMUA DATA SCREENING
GET http://localhost:4000/api/screenings


### MENDAPATKAN SEMUA DATA SCREENING BERDASARKAN NAMA
GET http://localhost:4000/api/screenings/user 2


### MELAKUKAN TEST DEPRESI
POST  http://localhost:4000/api/screenings
Content-Type: application/json

{
    "name" : "user 1",
    "tesdepresi" : 100
}


### MELAKUKAN TEST DEPRESI
PATCH  http://localhost:4000/api/screenings/1
Content-Type: application/json

{
    "name" : "user 1",
    "tesburnout" : 100
}




### MENDAPATKAN SEMUA DATA SCREENING
DELETE  http://localhost:4000/api/screenings/2
