### MENDAPATKAN SEMUA DATA USER
GET http://localhost:4000/api/users



### MENDAPATKAN SEMUA DATA USER
GET http://localhost:4000/api/users/9



### MEMBUAT USER BARU
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "firstName"     : "user",
    "lastName"      : "satu",
    "email"         : "user2@gmail.com",
    "password"      : "kesehatan",
    "re_password"   : "kesehatan"
}



### MENG DATA USER  BERDASARKAN ID
PATCH http://localhost:4000/api/users/14
Content-Type: application/json

{
    "tescemas" : 10
}



### DELETE DATA USER BERDASARKAN ID
DELETE http://localhost:4000/api/users/14

### LOGIN USER
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "kesehatan"
}