### MENDAPATKAN SEMUA DATA USER
GET http://localhost:4000/api/users



### MENDAPATKAN SEMUA DATA USER
GET http://localhost:4000/api/users/9



### MEMBUAT USER BARU
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "firstName"     : "kyouya1",
    "lastName"      : " ",
    "email"         : "kyouya1@gmail.com",
    "password"      : "kesehatan",
    "re_password"   : "kesehatan"
}



### MENG DATA USER  BERDASARKAN ID
PATCH http://localhost:4000/api/users/1
Content-Type: application/json

{
    "firstName"     : "kyouya",
    "lastName"      : "kun",
    "email"         : "kyouya@gmail.com",
    "password"      : "kesehatan",
    "re_password"   : "kesehatan"
}


### UPDATE DATA TEST USER BERDASARKAN ID
PATCH http://localhost:4000/api/users/test/1
Content-Type: application/json

{
    "tesdepresi" : 10,
    "tesstress" : 11,
    "tesbunuhdiri" : 25,
    "tescemas" : 30,
    "teskepribadian" : 45,
    "tesburnout" : 50
}


### DELETE DATA USER BERDASARKAN ID
DELETE http://localhost:4000/api/users/7

### LOGIN USER
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "kesehatan"
}